#define UTS_VERSION "#53 Fri Jul 4 17:35:09 EST 2003"
#define LINUX_COMPILE_TIME "17:35:09"
#define LINUX_COMPILE_BY "gerg"
#define LINUX_COMPILE_HOST "goober"
#define LINUX_COMPILE_DOMAIN "internal.moreton.com.au"
#define LINUX_COMPILER "gcc version 3.2.1"
